/** Every field a course record carries, with the value a brand-new course starts from. */
export const COURSE_DEFAULTS = {
  name: 'New course',
  code: '',
  categoryId: null,
  price: 0,
  description: '',
  status: 'inactive',
  published: false,
  level: 'All levels',
  capacity: 0,
  instructorIds: [],
  certificate: true,
  certificateType: 'classic',
  completionRule: 'All units must be completed',
  timeMode: 'days',
  timeLimitDays: 0,
  startDate: '',
  endDate: '',
  retainAccess: false,
  showInCatalog: true,
  publicSharing: false,
  enrollmentRequest: true,
  introVideo: null,
  cover: 'default',
  units: [],
}
