import { daysAgo, hoursAgo } from './utils'

const u = (id) => `u_${id}`
const c = (id) => `c_${id}`

export const DEFAULT_SETTINGS = {
  siteName: 'GA Healthcare Training - CNA Program',
  siteDescription:
    "GA Healthcare Training & Consulting offers expert-led CNA certification training founded by Dr. Yolaine Nozile, PhD, RN — building competent, career-ready nursing assistants for today's healthcare world.",
  domain: 'portal.gahealthcaretraining.com',
  website: 'https://gahealthcaretraining.com/',
  supportEmail: 'info@gahealthcaretraining.com',
  supportPhone: '(770) 872-8033',
  address: 'Atlanta, Georgia',
  logo: null,
  timezone: '(GMT -05:00) Eastern Time (US & Canada)',
  language: 'English (US)',
  dateFormat: 'DD/MM/YYYY',
  users: {
    selfRegistration: false,
    defaultUserType: 'Learner-Type',
    passwordMinLength: 8,
    forcePasswordReset: true,
    inactivityDays: 90,
    welcomeEmail: true,
  },
  courses: {
    defaultCompletionRule: 'All units must be completed',
    certificateEnabled: true,
    certificateValidity: '24 months',
    allowSelfEnrollment: false,
    showProgressBar: true,
  },
  security: {
    twoFactor: false,
    sessionTimeout: 60,
    loginAttempts: 5,
    auditLog: true,
  },
}

export const DEFAULT_USER_TYPES = [
  {
    id: 'ut_superadmin',
    name: 'SuperAdmin',
    role: 'superadmin',
    system: true,
    description: 'Full control of the portal, including settings and other administrators.',
  },
  {
    id: 'ut_admin',
    name: 'Admin-Type',
    role: 'admin',
    system: true,
    description: 'Manages users, courses, groups, branches and reports.',
  },
  {
    id: 'ut_trainer',
    name: 'Trainer-Type',
    role: 'instructor',
    system: true,
    description: 'Builds and delivers assigned courses, grades learners and views their reports.',
  },
  {
    id: 'ut_learner',
    name: 'Learner-Type',
    role: 'learner',
    system: true,
    description: 'Takes assigned courses and manages their own profile only.',
  },
]

export const DEFAULT_CATEGORIES = [
  { id: 'cat_orientation', name: 'Orientation', description: 'Program onboarding and policies' },
  { id: 'cat_cna', name: 'CNA Certification', description: 'Georgia CNA curriculum' },
  { id: 'cat_nclex', name: 'NCLEX Review', description: 'PN and RN exam preparation' },
  { id: 'cat_compliance', name: 'Compliance', description: 'HIPAA, OSHA, infection control' },
  { id: 'cat_ce', name: 'Continuing Education', description: 'Renewal and skills refreshers' },
]

const richText = (title, paragraphs, list) =>
  [
    `<h2>${title}</h2>`,
    ...paragraphs.map((p) => `<p>${p}</p>`),
    list ? `<ul>${list.map((i) => `<li>${i}</li>`).join('')}</ul>` : '',
  ].join('')

function cnaUnits() {
  return [
    { id: 'un_cna_s1', type: 'section', name: 'Module 1 — Role of the Nursing Assistant' },
    {
      id: 'un_cna_1',
      type: 'content',
      name: 'Welcome to the CNA Program',
      data: {
        html: richText(
          'Welcome to GA Healthcare Training',
          [
            'This program prepares you to sit for the Georgia CNA certification exam and to step confidently into a clinical role. Over the next weeks you will move through classroom theory, skills lab practice and supervised clinical hours.',
            'Everything you need — readings, videos, skill checklists and quizzes — lives inside this course. Work through the units in order; each one unlocks the next.',
          ],
          [
            '40 hours classroom instruction',
            '24 hours supervised clinical practice',
            'Skills lab check-offs with your instructor',
            'Final written and skills examination',
          ],
        ),
      },
    },
    {
      id: 'un_cna_2',
      type: 'content',
      name: 'Scope of Practice & Professional Conduct',
      data: {
        html: richText(
          'Scope of Practice',
          [
            'A Certified Nursing Assistant works under the supervision of a licensed nurse. Understanding what falls inside and outside your scope protects both you and your residents.',
          ],
          [
            'Assist with activities of daily living (ADLs)',
            'Measure and record vital signs',
            'Report changes in condition to the charge nurse',
            'Never administer medication or perform sterile procedures',
          ],
        ),
      },
    },
    {
      id: 'un_cna_3',
      type: 'video',
      name: 'Orientation Video — A Day on the Unit',
      data: { source: 'url', url: '', fileId: null, fileName: '', durationMin: 12 },
    },
    { id: 'un_cna_s2', type: 'section', name: 'Module 2 — Infection Control' },
    {
      id: 'un_cna_4',
      type: 'content',
      name: 'Standard Precautions',
      data: {
        html: richText(
          'Standard Precautions',
          [
            'Treat all blood and body fluids as potentially infectious. Hand hygiene remains the single most effective way to prevent the spread of infection in a healthcare setting.',
          ],
          [
            'Wash hands for at least 20 seconds before and after every resident contact',
            'Don gloves for any contact with body fluids, mucous membranes or broken skin',
            'Use gowns, masks and eye protection when splashing is possible',
            'Dispose of sharps immediately in a puncture-resistant container',
          ],
        ),
      },
    },
    {
      id: 'un_cna_5',
      type: 'document',
      name: 'Handwashing Skills Checklist (PDF)',
      data: { fileId: null, fileName: 'handwashing-checklist.pdf', fileType: 'application/pdf' },
    },
    {
      id: 'un_cna_6',
      type: 'test',
      name: 'Module 2 Quiz — Infection Control',
      data: {
        passingScore: 80,
        timeLimitMin: 15,
        maxAttempts: 3,
        shuffle: true,
        questions: [
          {
            id: 'q1',
            type: 'single',
            text: 'What is the minimum recommended duration for hand washing?',
            points: 1,
            options: [
              { id: 'o1', text: '5 seconds', correct: false },
              { id: 'o2', text: '20 seconds', correct: true },
              { id: 'o3', text: '60 seconds', correct: false },
              { id: 'o4', text: 'Until the water runs clear', correct: false },
            ],
          },
          {
            id: 'q2',
            type: 'multiple',
            text: 'Which items are part of personal protective equipment (PPE)? Select all that apply.',
            points: 2,
            options: [
              { id: 'o1', text: 'Gloves', correct: true },
              { id: 'o2', text: 'Gown', correct: true },
              { id: 'o3', text: 'Stethoscope', correct: false },
              { id: 'o4', text: 'Face shield', correct: true },
            ],
          },
          {
            id: 'q3',
            type: 'truefalse',
            text: 'Gloves may be reused between two residents if they look clean.',
            points: 1,
            options: [
              { id: 'o1', text: 'True', correct: false },
              { id: 'o2', text: 'False', correct: true },
            ],
          },
          {
            id: 'q4',
            type: 'text',
            text: 'In your own words, describe when you would wear a gown during resident care.',
            points: 1,
            options: [],
          },
        ],
      },
    },
    { id: 'un_cna_s3', type: 'section', name: 'Module 3 — Vital Signs & Clinical Skills' },
    {
      id: 'un_cna_7',
      type: 'content',
      name: 'Measuring & Recording Vital Signs',
      data: {
        html: richText(
          'Vital Signs',
          [
            'Accurate vital signs give the nursing team an early warning of a change in condition. Record immediately — never rely on memory — and report anything outside the normal range.',
          ],
          [
            'Temperature: 97.0°F – 99.0°F oral',
            'Pulse: 60 – 100 beats per minute',
            'Respirations: 12 – 20 breaths per minute',
            'Blood pressure: below 120/80 mmHg is optimal',
          ],
        ),
      },
    },
    {
      id: 'un_cna_8',
      type: 'assignment',
      name: 'Skills Lab — Vital Signs Practice Log',
      data: {
        instructions:
          'Complete 10 supervised vital sign measurements in the skills lab. Upload your signed practice log (PDF or photo) for your instructor to review.',
        dueDays: 14,
        allowFileUpload: true,
        maxScore: 100,
      },
    },
    {
      id: 'un_cna_9',
      type: 'ilt',
      name: 'Clinical Rotation — Week 1',
      data: {
        sessions: [
          {
            id: 's1',
            name: 'Clinical Day 1 — Long-term care facility',
            start: daysAgo(-7),
            end: daysAgo(-7),
            location: 'Peachtree Senior Living, Atlanta GA',
            capacity: 12,
            instructor: 'E. Elisme',
          },
          {
            id: 's2',
            name: 'Clinical Day 2 — Skills lab check-off',
            start: daysAgo(-10),
            end: daysAgo(-10),
            location: 'GA Healthcare Training Center — Lab B',
            capacity: 12,
            instructor: 'Y. Nozile',
          },
        ],
      },
    },
    {
      id: 'un_cna_10',
      type: 'survey',
      name: 'Program Feedback Survey',
      data: {
        questions: [
          {
            id: 'sq1',
            type: 'single',
            text: 'How confident do you feel performing vital signs unsupervised?',
            options: [
              { id: 'a', text: 'Very confident' },
              { id: 'b', text: 'Somewhat confident' },
              { id: 'c', text: 'Not yet confident' },
            ],
          },
          { id: 'sq2', type: 'text', text: 'What would you like more practice time on?', options: [] },
        ],
      },
    },
  ]
}

function nclexUnits(kind) {
  return [
    { id: `un_${kind}_s1`, type: 'section', name: 'Exam Blueprint & Study Plan' },
    {
      id: `un_${kind}_1`,
      type: 'content',
      name: `Understanding the NCLEX-${kind.toUpperCase()} Test Plan`,
      data: {
        html: richText(
          `NCLEX-${kind.toUpperCase()} Test Plan`,
          [
            'The exam is built around four Client Needs categories. Knowing how questions are weighted lets you spend your study hours where they count.',
          ],
          [
            'Safe and Effective Care Environment',
            'Health Promotion and Maintenance',
            'Psychosocial Integrity',
            'Physiological Integrity',
          ],
        ),
      },
    },
    {
      id: `un_${kind}_2`,
      type: 'webcontent',
      name: 'Recommended Reading — Test-Taking Strategies',
      data: { url: 'https://gahealthcaretraining.com/', openInNewTab: true },
    },
    {
      id: `un_${kind}_3`,
      type: 'test',
      name: 'Diagnostic Practice Test',
      data: {
        passingScore: 75,
        timeLimitMin: 45,
        maxAttempts: 2,
        shuffle: true,
        questions: [
          {
            id: 'q1',
            type: 'single',
            text: 'A client reports chest pain radiating to the left arm. What is the nurse’s first action?',
            points: 1,
            options: [
              { id: 'o1', text: 'Call the family', correct: false },
              { id: 'o2', text: 'Assess vital signs and notify the provider', correct: true },
              { id: 'o3', text: 'Document the complaint at end of shift', correct: false },
              { id: 'o4', text: 'Encourage ambulation', correct: false },
            ],
          },
          {
            id: 'q2',
            type: 'multiple',
            text: 'Which findings suggest fluid volume deficit? Select all that apply.',
            points: 2,
            options: [
              { id: 'o1', text: 'Dry mucous membranes', correct: true },
              { id: 'o2', text: 'Bounding pulse', correct: false },
              { id: 'o3', text: 'Decreased urine output', correct: true },
              { id: 'o4', text: 'Poor skin turgor', correct: true },
            ],
          },
        ],
      },
    },
  ]
}

export function buildSeed() {
  const users = [
    {
      id: u('nozile'),
      firstName: 'Yolaine',
      lastName: 'Nozile',
      email: 'ynozile@gahealthcaretraining.com',
      password: 'Ga@2026!',
      role: 'superadmin',
      userType: 'SuperAdmin',
      active: true,
      bio: 'Founder & Program Director. PhD, RN.',
      phone: '(770) 872-8033',
      branchId: 'br_atlanta',
      groupIds: [],
      registeredAt: daysAgo(127),
      lastLogin: hoursAgo(16),
      avatar: null,
    },
    {
      id: u('zahid'),
      firstName: 'Zahid',
      lastName: 'Ali',
      email: 'zahidaliyaftali999@gmail.com',
      password: 'Ga@2026!',
      role: 'superadmin',
      userType: 'SuperAdmin',
      active: true,
      bio: 'Portal administrator.',
      phone: '',
      branchId: 'br_atlanta',
      groupIds: [],
      registeredAt: hoursAgo(16),
      lastLogin: hoursAgo(1),
      avatar: null,
    },
    {
      id: u('simmons'),
      firstName: 'Barbara',
      lastName: 'Simmons',
      email: 'barbara.simmons@allianthealth.org',
      password: 'Welcome1',
      role: 'admin',
      userType: 'Admin-Type',
      active: true,
      bio: 'Enrollment and student records.',
      phone: '',
      branchId: 'br_atlanta',
      groupIds: ['g_staff'],
      registeredAt: daysAgo(42),
      lastLogin: null,
      avatar: null,
    },
    {
      id: u('elisme'),
      firstName: 'Edwidge',
      lastName: 'Elisme',
      email: 'drelisme@elismeconsultingservices.com',
      password: 'Welcome1',
      role: 'instructor',
      userType: 'Trainer-Type',
      active: true,
      bio: 'Clinical instructor — skills lab and clinical rotations.',
      phone: '',
      branchId: 'br_atlanta',
      groupIds: ['g_staff'],
      registeredAt: daysAgo(117),
      lastLogin: daysAgo(3),
      avatar: null,
    },
    {
      id: u('goodrigge'),
      firstName: 'Alicia',
      lastName: 'Goodrigge',
      email: 'goodnursingconsultants@gmail.com',
      password: 'Welcome1',
      role: 'learner',
      userType: 'Learner-Type',
      active: false,
      bio: '',
      phone: '',
      branchId: 'br_atlanta',
      groupIds: ['g_fall_cna'],
      registeredAt: daysAgo(99),
      lastLogin: null,
      avatar: null,
    },
    {
      id: u('marcus'),
      firstName: 'Marcus',
      lastName: 'Bennett',
      email: 'marcus.bennett@example.com',
      password: 'Welcome1',
      role: 'learner',
      userType: 'Learner-Type',
      active: true,
      bio: '',
      phone: '',
      branchId: 'br_atlanta',
      groupIds: ['g_fall_cna'],
      registeredAt: daysAgo(31),
      lastLogin: hoursAgo(20),
      avatar: null,
    },
    {
      id: u('tasha'),
      firstName: 'Tasha',
      lastName: 'Rivera',
      email: 'tasha.rivera@example.com',
      password: 'Welcome1',
      role: 'learner',
      userType: 'Learner-Type',
      active: true,
      bio: '',
      phone: '',
      branchId: 'br_savannah',
      groupIds: ['g_fall_cna'],
      registeredAt: daysAgo(29),
      lastLogin: hoursAgo(40),
      avatar: null,
    },
    {
      id: u('devon'),
      firstName: 'Devon',
      lastName: 'Clarke',
      email: 'devon.clarke@example.com',
      password: 'Welcome1',
      role: 'learner',
      userType: 'Learner-Type',
      active: true,
      bio: '',
      phone: '',
      branchId: 'br_savannah',
      groupIds: ['g_nclex'],
      registeredAt: daysAgo(12),
      lastLogin: hoursAgo(72),
      avatar: null,
    },
  ]

  const courses = [
    {
      id: c('cna'),
      name: 'Nursing Assistant Program (CNA)',
      code: 'NA01',
      categoryId: 'cat_orientation',
      price: 1325,
      description:
        'Launch your healthcare career with foundational skills in patient care, safety, vital signs, and clinical communication. This program prepares you to sit for the CNA certification exam and enter the workforce with confidence and competence.',
      status: 'active',
      published: true,
      level: 'Beginner',
      capacity: 24,
      instructorIds: [u('elisme')],
      certificate: true,
      completionRule: 'All units must be completed',
      timeLimitDays: 90,
      createdAt: daysAgo(120),
      updatedAt: daysAgo(40),
      cover: 'cna',
      units: cnaUnits(),
    },
    {
      id: c('nclexpn'),
      name: 'NCLEX PN REVIEW COURSE',
      code: 'PN01',
      categoryId: 'cat_nclex',
      price: 700,
      description:
        'A focused review for practical nursing candidates: test plan breakdown, content refreshers and timed practice sets.',
      status: 'active',
      published: true,
      level: 'Intermediate',
      capacity: 30,
      instructorIds: [u('elisme')],
      certificate: true,
      completionRule: 'All units must be completed',
      timeLimitDays: 60,
      createdAt: daysAgo(80),
      updatedAt: daysAgo(74),
      cover: 'nclex',
      units: nclexUnits('pn'),
    },
    {
      id: c('nclexrn'),
      name: 'NCLEX RN REVIEW',
      code: 'RN01',
      categoryId: 'cat_nclex',
      price: 900,
      description:
        'Registered nurse exam preparation covering all four Client Needs categories with diagnostic and mastery testing.',
      status: 'active',
      published: true,
      level: 'Advanced',
      capacity: 30,
      instructorIds: [u('elisme')],
      certificate: true,
      completionRule: 'All units must be completed',
      timeLimitDays: 60,
      createdAt: daysAgo(80),
      updatedAt: daysAgo(74),
      cover: 'nclex',
      units: nclexUnits('rn'),
    },
    {
      id: c('infection'),
      name: 'Infection Control & Standard Precautions',
      code: 'IC10',
      categoryId: 'cat_compliance',
      price: 0,
      description: 'Annual compliance refresher required for all clinical staff and students.',
      status: 'active',
      published: true,
      level: 'All levels',
      capacity: 0,
      instructorIds: [u('elisme')],
      certificate: true,
      completionRule: 'All units must be completed',
      timeLimitDays: 30,
      createdAt: daysAgo(60),
      updatedAt: daysAgo(21),
      cover: 'compliance',
      units: [
        {
          id: 'un_ic_1',
          type: 'content',
          name: 'Chain of Infection',
          data: {
            html: richText(
              'The Chain of Infection',
              [
                'Breaking any single link stops transmission. Most breaks happen at the mode of transmission link — which is where hand hygiene and PPE do their work.',
              ],
              [
                'Infectious agent',
                'Reservoir',
                'Portal of exit',
                'Mode of transmission',
                'Portal of entry',
                'Susceptible host',
              ],
            ),
          },
        },
        {
          id: 'un_ic_2',
          type: 'test',
          name: 'Compliance Check',
          data: {
            passingScore: 80,
            timeLimitMin: 10,
            maxAttempts: 0,
            shuffle: false,
            questions: [
              {
                id: 'q1',
                type: 'truefalse',
                text: 'Hand hygiene is required both before and after glove use.',
                points: 1,
                options: [
                  { id: 'o1', text: 'True', correct: true },
                  { id: 'o2', text: 'False', correct: false },
                ],
              },
            ],
          },
        },
      ],
    },
    {
      id: c('hipaa'),
      name: 'HIPAA & Patient Privacy Basics',
      code: 'HP05',
      categoryId: 'cat_compliance',
      price: 0,
      description: 'What protected health information is, and how to handle it on the unit and online.',
      status: 'active',
      published: true,
      level: 'All levels',
      capacity: 0,
      instructorIds: [],
      certificate: true,
      completionRule: 'All units must be completed',
      timeLimitDays: 30,
      createdAt: daysAgo(55),
      updatedAt: daysAgo(30),
      cover: 'compliance',
      units: [
        {
          id: 'un_hp_1',
          type: 'content',
          name: 'What counts as PHI?',
          data: {
            html: richText(
              'Protected Health Information',
              [
                'Any information that can identify a patient and relates to their care or payment for care is protected — in charts, in conversation and on your phone.',
              ],
              [
                'Names, addresses and dates',
                'Medical record and account numbers',
                'Photographs',
                'Anything posted to social media',
              ],
            ),
          },
        },
      ],
    },
    {
      id: c('onboarding'),
      name: 'Onboarding Package',
      code: '',
      categoryId: null,
      price: 0,
      description: 'Staff onboarding bundle — draft.',
      status: 'inactive',
      published: false,
      level: 'All levels',
      capacity: 0,
      instructorIds: [],
      certificate: false,
      completionRule: 'All units must be completed',
      timeLimitDays: 0,
      createdAt: daysAgo(10),
      updatedAt: daysAgo(10),
      cover: 'default',
      units: [],
    },
  ]

  const branches = [
    {
      id: 'br_atlanta',
      name: 'Atlanta Campus',
      description: 'Main training center and skills lab',
      location: 'Atlanta, GA',
      active: true,
      createdAt: daysAgo(127),
    },
    {
      id: 'br_savannah',
      name: 'Savannah Campus',
      description: 'Satellite classroom',
      location: 'Savannah, GA',
      active: true,
      createdAt: daysAgo(60),
    },
  ]

  const groups = [
    {
      id: 'g_fall_cna',
      name: 'Fall 2026 CNA Cohort',
      description: 'Students enrolled in the September CNA class',
      key: 'FALL26',
      courseIds: [c('cna'), c('infection')],
      createdAt: daysAgo(35),
    },
    {
      id: 'g_nclex',
      name: 'NCLEX Review Group',
      description: 'PN and RN exam candidates',
      key: 'NCLEX',
      courseIds: [c('nclexpn'), c('nclexrn')],
      createdAt: daysAgo(20),
    },
    {
      id: 'g_staff',
      name: 'Staff & Instructors',
      description: 'Internal team compliance training',
      key: 'STAFF',
      courseIds: [c('hipaa'), c('infection')],
      createdAt: daysAgo(50),
    },
  ]

  const enrollments = [
    {
      id: 'en_1',
      userId: u('marcus'),
      courseId: c('cna'),
      enrolledAt: daysAgo(30),
      completedUnits: ['un_cna_1', 'un_cna_2', 'un_cna_4'],
      status: 'in_progress',
      score: null,
      completedAt: null,
      timeSpentMin: 145,
    },
    {
      id: 'en_2',
      userId: u('tasha'),
      courseId: c('cna'),
      enrolledAt: daysAgo(28),
      completedUnits: ['un_cna_1'],
      status: 'in_progress',
      score: null,
      completedAt: null,
      timeSpentMin: 40,
    },
    {
      id: 'en_3',
      userId: u('devon'),
      courseId: c('nclexpn'),
      enrolledAt: daysAgo(11),
      completedUnits: [],
      status: 'not_started',
      score: null,
      completedAt: null,
      timeSpentMin: 0,
    },
    {
      id: 'en_4',
      userId: u('goodrigge'),
      courseId: c('cna'),
      enrolledAt: daysAgo(90),
      completedUnits: [],
      status: 'not_started',
      score: null,
      completedAt: null,
      timeSpentMin: 0,
    },
    {
      id: 'en_5',
      userId: u('elisme'),
      courseId: c('hipaa'),
      enrolledAt: daysAgo(40),
      completedUnits: ['un_hp_1'],
      status: 'completed',
      score: 100,
      completedAt: daysAgo(38),
      timeSpentMin: 25,
    },
  ]

  const notifications = [
    {
      id: 'nt_1',
      name: 'Welcome email with login details',
      event: 'User is created',
      recipient: 'The user',
      active: true,
      subject: 'Your GA Healthcare Training account is ready',
      body: 'Hi {user_name}, an account has been created for you at {site_name}. Sign in at {login_url} with your email and the password provided by your administrator.',
      createdAt: daysAgo(120),
    },
    {
      id: 'nt_2',
      name: 'Course assigned',
      event: 'User is enrolled in course',
      recipient: 'The user',
      active: true,
      subject: 'You have been enrolled in {course_name}',
      body: 'Hi {user_name}, you now have access to {course_name}. Log in to begin.',
      createdAt: daysAgo(120),
    },
    {
      id: 'nt_3',
      name: 'Course completion certificate',
      event: 'User completes course',
      recipient: 'The user',
      active: true,
      subject: 'Congratulations on completing {course_name}',
      body: 'Well done {user_name}! Your certificate for {course_name} is available in your profile.',
      createdAt: daysAgo(118),
    },
    {
      id: 'nt_4',
      name: 'Inactivity reminder',
      event: 'User has not logged in for 14 days',
      recipient: 'The user',
      active: false,
      subject: 'We miss you at {site_name}',
      body: 'Hi {user_name}, your course {course_name} is still waiting for you.',
      createdAt: daysAgo(90),
    },
  ]

  const messages = [
    {
      id: 'm_1',
      fromId: u('nozile'),
      toId: u('zahid'),
      subject: 'Fall cohort roster',
      body: 'Please confirm the Fall 2026 CNA roster is complete before Friday so we can order the skills lab supplies.',
      sentAt: hoursAgo(15),
      read: false,
    },
    {
      id: 'm_2',
      fromId: u('elisme'),
      toId: u('zahid'),
      subject: 'Clinical rotation dates',
      body: 'Peachtree Senior Living confirmed both clinical days. I have added the sessions to the CNA course.',
      sentAt: daysAgo(2),
      read: true,
    },
  ]

  const events = [
    { id: 'ev_1', type: 'login', actorId: u('zahid'), text: 'signed in', at: hoursAgo(1) },
    { id: 'ev_2', type: 'login', actorId: u('zahid'), text: 'signed in (2 times)', at: hoursAgo(16) },
    {
      id: 'ev_3',
      type: 'user',
      actorId: u('nozile'),
      targetId: u('zahid'),
      text: 'registered a new user',
      at: hoursAgo(16),
    },
    {
      id: 'ev_4',
      type: 'progress',
      actorId: u('marcus'),
      text: 'completed unit Standard Precautions',
      at: hoursAgo(20),
    },
    {
      id: 'ev_5',
      type: 'course',
      actorId: u('elisme'),
      text: 'updated course Nursing Assistant Program (CNA)',
      at: daysAgo(3),
    },
    {
      id: 'ev_6',
      type: 'completion',
      actorId: u('elisme'),
      text: 'completed course HIPAA & Patient Privacy Basics',
      at: daysAgo(38),
    },
  ]

  const submissions = [
    {
      id: 'sub_1',
      type: 'assignment',
      courseId: c('cna'),
      unitId: 'un_cna_8',
      userId: u('marcus'),
      submittedAt: hoursAgo(30),
      text: 'Completed 10 supervised readings in Lab B, log signed by instructor.',
      fileId: null,
      fileName: 'vitals-log-marcus.pdf',
      status: 'pending',
      grade: null,
      feedback: '',
    },
  ]

  return {
    version: 1,
    settings: DEFAULT_SETTINGS,
    userTypes: DEFAULT_USER_TYPES,
    categories: DEFAULT_CATEGORIES,
    users,
    courses,
    branches,
    groups,
    enrollments,
    notifications,
    messages,
    events,
    submissions,
    certificates: [
      { id: 'cert_1', userId: u('elisme'), courseId: c('hipaa'), issuedAt: daysAgo(38), code: 'GA-HP05-0031' },
    ],
  }
}
