// Writes server/seed-data.js: the data a brand-new shared database starts with
// (the portal's sample content plus the courses copied from TalentLMS).
// Run with `npm run seed:export` after changing src/lib/seed.js or the course import.
import { writeFileSync } from 'node:fs'
import { createServer } from 'vite'

const vite = await createServer({ server: { middlewareMode: true }, appType: 'custom', logLevel: 'error' })
try {
  const { buildSeed } = await vite.ssrLoadModule('/src/lib/seed.js')
  const { applyCourseImport } = await vite.ssrLoadModule('/src/lib/importedCourses.js')
  const data = applyCourseImport(buildSeed())
  writeFileSync(
    'server/seed-data.js',
    `// Generated by scripts/export-seed.mjs — do not edit by hand.\n// Starting data for a new shared database; passwords are hashed when it is loaded.\nexport default ${JSON.stringify(data)}\n`,
  )
  console.log(`server/seed-data.js: ${data.users.length} users, ${data.courses.length} courses`)
} finally {
  await vite.close()
}
